# Generated by Django 3.2 on 2022-11-17 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproductapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creded', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 12, 10, 43, 603949))),
                ('fullname', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
