# Generated by Django 3.2 on 2022-11-18 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproductapp', '0002_product_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_manager',
            name='creded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 19, 2, 31, 17, 467345)),
        ),
    ]
