# Generated by Django 4.1.3 on 2022-12-07 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myproductapp", "0003_alter_product_manager_creded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_manager",
            name="creded",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2022, 12, 7, 11, 14, 40, 231979)
            ),
        ),
    ]
